In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from glob import glob
from src.session_loader import Session

In [2]:
reg_matrix = np.load(r'G:\Projects\helping_behavior\Analysis\Calcium-Imaging-Analysis\processed-data\Oct_2021\registration\5593_accepted_only_registered_ids.npy')
indexing = np.load(r'G:\Projects\helping_behavior\Analysis\Calcium-Imaging-Analysis\processed-data\Oct_2021\registration\5593_accepted_only_session_indexing.npy', allow_pickle=True).item()
print(reg_matrix.shape, indexing)

(1440, 10) {'HBTD6': 0, 'HBTD5': 1, 'Pool': 2, 'HBTD2': 3, 'Empty': 4, 'HBTD4': 5, 'Stranger': 6, 'HBTD1': 7, 'Toy': 8, 'HBTD3': 9}

In [3]:
session_file = pd.read_csv('G:\Projects\helping_behavior\Analysis\Calcium-Imaging-Analysis\data\log\SESSION_FILE_event_associated_cells_definition_2024-10-25_10-51-23.csv')
session_file.head()

,Excluded,Session,Cohort,Date,Mouse,Pair,Criteria,Sex,Final Outcome,Session Outcome,...,USV helper,USV victim,AdaNotes,Comments,Num of Liberation cells,% of Liberation cells,Liberation Associated Cells Metadata Path,Num of Random cells,% of Random cells,Random Associated Cells Metadata Path
0,False,HBTD1,Jan_2024,15.01.2024,8000,8000-7999,SSCW,M,H,NH,...,NaN,NaN,NaN,NaN,NaN,NaN,processed-data/METADATA_Liberation_event_assoc...,NaN,NaN,processed-data/METADATA_Random_event_associate...
1,False,HBTD3,Jan_2024,17.01.2024,8000,8000-7999,SSCW,M,H,H,...,NaN,NaN,NaN,NaN,5.0,13.513514,processed-data/METADATA_Liberation_event_assoc...,5.0,13.513514,processed-data/METADATA_Random_event_associate...
2,False,HBTD4,Jan_2024,18.01.2024,8000,8000-7999,SSCW,M,H,H,...,NaN,NaN,NaN,NaN,3.0,11.538462,processed-data/METADATA_Liberation_event_assoc...,3.0,11.538462,processed-data/METADATA_Random_event_associate...
3,False,HBTD5,Jan_2024,19.01.2024,8000,8000-7999,SSCW,M,H,H,...,NaN,NaN,NaN,NaN,4.0,16.666667,processed-data/METADATA_Liberation_event_assoc...,4.0,16.666667,processed-data/METADATA_Random_event_associate...
4,False,HBTD6,Jan_2024,20.01.2024,8000,8000-7999,SSCW,M,H,H,...,NaN,NaN,NaN,NaN,3.0,13.636364,processed-data/METADATA_Liberation_event_assoc...,3.0,13.636364,processed-data/METADATA_Random_event_associate...

In [4]:
session_file = session_file[session_file['Mouse'] == 5593]
session_file.head()

,Excluded,Session,Cohort,Date,Mouse,Pair,Criteria,Sex,Final Outcome,Session Outcome,...,USV helper,USV victim,AdaNotes,Comments,Num of Liberation cells,% of Liberation cells,Liberation Associated Cells Metadata Path,Num of Random cells,% of Random cells,Random Associated Cells Metadata Path
79,False,HBTD1,Oct_2021,23.10.2021,5593,5593-5756,SSCW,F,H,NH,...,NaN,NaN,NaN,NaN,NaN,NaN,processed-data/METADATA_Liberation_event_assoc...,NaN,NaN,processed-data/METADATA_Random_event_associate...
83,False,HBTD2,Oct_2021,24.10.2021,5593,5593-5756,SSCW,F,H,H,...,NaN,NaN,12.5,(ADA NOTE: 12.5 min),59.0,11.919192,processed-data/METADATA_Liberation_event_assoc...,59.0,11.919192,processed-data/METADATA_Random_event_associate...
87,False,HBTD3,Oct_2021,25.10.2021,5593,5593-5756,SSCW,F,H,H,...,NaN,NaN,4.8,(ADA NOTE: 4.8 min),36.0,11.764706,processed-data/METADATA_Liberation_event_assoc...,36.0,11.764706,processed-data/METADATA_Random_event_associate...
90,False,HBTD4,Oct_2021,27.10.2021,5593,5593-5756,SSCW,F,H,H,...,NaN,NaN,0.5,cover of the victims box fell into the box (A...,30.0,21.126761,processed-data/METADATA_Liberation_event_assoc...,30.0,21.126761,processed-data/METADATA_Random_event_associate...
94,False,HBTD5,Oct_2021,28.10.2021,5593,5593-5756,SSCW,F,H,H,...,NaN,NaN,0.6,(ADA NOTE 0.6 min) Behavior videos end at 4s. ...,19.0,15.200000,processed-data/METADATA_Liberation_event_assoc...,19.0,15.200000,processed-data/METADATA_Random_event_associate...

In [5]:
for i, row in session_file.iterrows():
    session = Session(row)
    positions = session.extract_neuron_positions(session.get_neuron_labels())
    print(positions.shape)
    break